//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 由 StupidDNS.rc 使用
//
#define IDM_ABOUTBOX       0x0010
#define IDD_ABOUTBOX 100
#define IDS_ABOUTBOX     101
#define IDD_STUPIDDNS_DIALOG     1001
#define IDR_MAINFRAME  128
#define IDI_APP_LOGO   129  // 应用程序Logo图标
#define IDC_BTN_START    1002
#define IDC_BTN_STOP        1003
#define IDC_EDIT_PORT     1004
#define IDC_STATIC_STATUS 1005
#define IDC_LIST_LOG 1006
#define IDC_BTN_CLEAR_LOG 1007
#define IDC_BTN_EXPORT_LOG     1008
#define IDC_BTN_DNS_SETTINGS   1009
#define IDC_BTN_ADVANCED    1011
#define IDC_BTN_ABOUT        1012
#define IDC_STATIC_TOTAL 1013
#define IDC_STATIC_CACHE_RATE   1014
#define IDC_STATIC_DOMESTIC  1015
#define IDC_STATIC_FOREIGN 1016
#define IDC_STATIC_RUNTIME 1017
#define IDC_STATIC_AVG_RESPONSE  1018
#define IDC_BTN_SET_SYSTEM_DNS 1058  // 设置系统DNS按钮

// DNS服务器管理对话框
#define IDD_DNS_SETTINGS_DIALOG 131
#define IDC_LIST_DNS_SERVERS      1019
#define IDC_BTN_ADD_DNS      1020
#define IDC_BTN_DELETE_DNS          1021
#define IDC_BTN_EDIT_DNS    1022
#define IDC_BTN_TEST_DNS     1023
#define IDC_BTN_TEST_ALL_DNS        1024
#define IDC_BTN_IMPORT_DNS          1025
#define IDC_BTN_EXPORT_DNS_LIST     1026
#define IDC_BTN_RESET_DNS       1027
#define IDC_CHECK_AUTO_TEST         1028

// 高级选项对话框
#define IDD_ADVANCED_DIALOG    133
#define IDC_CHECK_ENABLE_CACHE   1039
#define IDC_EDIT_CACHE_SIZE       1040
#define IDC_EDIT_CACHE_TTL   1041
#define IDC_CHECK_POLLUTION_DETECT  1042
#define IDC_EDIT_QUERY_TIMEOUT      1043
#define IDC_EDIT_CONCURRENT_QUERIES 1044
#define IDC_CHECK_ENABLE_LOG  1045
#define IDC_EDIT_LOG_PATH           1046
#define IDC_BTN_BROWSE_LOG  1047
#define IDC_CHECK_AUTO_START        1048
#define IDC_CHECK_MINIMIZE_TO_TRAY  1049
#define IDC_COMBO_LOG_LEVEL    1050
#define IDC_BTN_RESET_ADVANCED      1051

// 关于对话框
#define IDD_ABOUT_DIALOG      134
#define IDC_STATIC_LOGO    1052
#define IDC_STATIC_APP_NAME 1053
#define IDC_STATIC_VERSION   1054
#define IDC_STATIC_COPYRIGHT        1055
#define IDC_STATIC_DESCRIPTION      1056
#define IDC_LINK_GITHUB    1057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE   136
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE      1059
#define _APS_NEXT_SYMED_VALUE 102
#endif
#endif
